#!/usr/bin/env python3
"""PreToolUse hook for the rforge plugin.

Runs on every Write/Edit call and applies R-package-aware rules:

  1. WARN  - editing R/*.R reminds the developer to update NAMESPACE/DESCRIPTION
             when adding/removing exports.
  2. BLOCK - editing man/*.Rd is always wrong; those files are regenerated by
             roxygen2 via devtools::document() and any hand-edits will be lost.
  3. WARN  - DESCRIPTION Version: bumps that don't match SemVer (X.Y.Z).
  4. WARN  - edits outside the current worktree (verbatim port of craft's rule).

Exit codes (PreToolUse semantics):
  0 - allow the tool call (warnings still printed to stderr).
  2 - block the tool call (Claude Code shows the stderr message to the user).

Designed to be diagnostic, not adversarial. Only the man/*.Rd rule blocks;
the rest warn.
"""

import json
import os
import re
import subprocess
import sys


SEMVER_RE = re.compile(r"^\d+\.\d+(\.\d+)?(-[A-Za-z0-9.]+)?$")


def get_git_toplevel():
    """Return the git toplevel directory, or None if not in a repo."""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True, text=True, timeout=5,
        )
        if result.returncode == 0:
            return result.stdout.strip()
    except (subprocess.TimeoutExpired, FileNotFoundError):
        pass
    return None


def warn(msg, *details):
    print(f"⚠️  {msg}", file=sys.stderr)
    for line in details:
        print(f"   {line}", file=sys.stderr)


def block(msg, *details):
    print(f"🛑 {msg}", file=sys.stderr)
    for line in details:
        print(f"   {line}", file=sys.stderr)
    sys.exit(2)


def proposed_content(parsed):
    """Return the post-edit file content the tool intends to write.

    Write    -> 'content'
    Edit     -> 'new_string' (a fragment, not the whole file — best effort).
    Anything else -> empty string.
    """
    if "content" in parsed:
        return parsed.get("content", "") or ""
    if "new_string" in parsed:
        return parsed.get("new_string", "") or ""
    return ""


def check_outside_worktree(file_path, toplevel):
    """Rule 4: warn when writing outside the current git toplevel."""
    if not toplevel:
        return
    if "/.git-worktrees/" not in os.getcwd():
        return
    if file_path.startswith(toplevel + os.sep) or file_path == toplevel:
        return
    warn(
        "Writing outside worktree",
        f"File:     {file_path}",
        f"Worktree: {toplevel}",
        f"Consider: cd {toplevel}",
    )


def check_man_rd(file_path):
    """Rule 2: block hand-edits to roxygen-generated man/*.Rd files."""
    rel = os.path.basename(os.path.dirname(file_path))
    if rel == "man" and file_path.endswith(".Rd"):
        block(
            "Refusing to edit roxygen-generated man/*.Rd file",
            f"File:    {file_path}",
            "Reason:  man/*.Rd is regenerated by devtools::document().",
            "Instead: edit the @param/@return/@examples roxygen comments in R/",
            "         and run devtools::document() to regenerate.",
        )


def check_r_source_reminder(file_path):
    """Rule 1: remind the developer about NAMESPACE/DESCRIPTION on R/ edits.

    Cannot verify in a single PreToolUse call whether NAMESPACE will also be
    updated later in the session — this is a reminder, not a check.
    """
    parts = file_path.split(os.sep)
    if "R" in parts:
        idx = parts.index("R")
        if idx >= 0 and idx < len(parts) - 1 and parts[-1].endswith(".R"):
            warn(
                "Editing R/ source — remember to keep package metadata in sync",
                f"File: {file_path}",
                "If you added/removed @export tags: run devtools::document().",
                "If you added a new dependency: add it to DESCRIPTION (Imports:).",
            )


def check_description_version(file_path, content):
    """Rule 3: warn when a DESCRIPTION Version: line isn't valid SemVer."""
    if os.path.basename(file_path) != "DESCRIPTION":
        return
    if not content:
        return
    for line in content.splitlines():
        if line.startswith("Version:"):
            version = line.split(":", 1)[1].strip()
            if not SEMVER_RE.match(version):
                warn(
                    f"DESCRIPTION Version '{version}' is not SemVer-compatible",
                    "Expected:  MAJOR.MINOR.PATCH (e.g. 1.2.0 or 1.2.0-rc1)",
                    "CRAN policy: prefers strict X.Y.Z bumps for releases.",
                )
            return


def main():
    # Claude Code passes the hook payload as JSON on stdin:
    #   { "session_id": "...", "tool_name": "Write",
    #     "tool_input": { "file_path": "...", "content": "..." }, ... }
    # See ~/.claude/hooks/branch-guard.sh for the canonical contract.
    try:
        payload = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError):
        return

    tool_name = payload.get("tool_name", "")
    if tool_name not in ("Write", "Edit"):
        return

    parsed = payload.get("tool_input", {}) or {}
    file_path = parsed.get("file_path", "")
    if not file_path:
        return

    file_path = os.path.abspath(file_path)
    toplevel = get_git_toplevel()
    if toplevel:
        toplevel = os.path.abspath(toplevel)

    check_man_rd(file_path)
    check_outside_worktree(file_path, toplevel)
    check_r_source_reminder(file_path)
    check_description_version(file_path, proposed_content(parsed))


if __name__ == "__main__":
    main()
