#!/usr/bin/env python3
"""
Generate Markdown API references from the lib/ Python modules.

Reads `lib/discovery.py` and `lib/deps.py`, introspects their public
functions and dataclasses, and writes:
  - docs/reference/discovery.md
  - docs/reference/deps.md

Each generated page is a deterministic dump of signature + docstring; it
is regeneratable from source at any time. The mkdocs nav points at these
files (see mkdocs.yml).

Usage:
    python3 scripts/gen_lib_reference.py            # write the files
    python3 scripts/gen_lib_reference.py --check    # exit 1 if out of date

The --check mode is useful in CI to ensure the reference docs stay in sync
with the source.
"""

from __future__ import annotations

import argparse
import importlib
import inspect
import re
import sys
import textwrap
from dataclasses import fields, is_dataclass
from pathlib import Path
from types import ModuleType

REPO_ROOT = Path(__file__).resolve().parent.parent
LIB_DIR = REPO_ROOT / "lib"  # kept for the doc-output destination
OUT_DIR = REPO_ROOT / "docs" / "reference"

MODULES = ["lib.discovery", "lib.deps", "lib.status", "lib.init", "lib.rcmd"]


def _public_members(module: ModuleType) -> tuple[list, list]:
    """Return (functions, dataclasses) defined IN this module (not imported)."""
    funcs, dcs = [], []
    for name, obj in inspect.getmembers(module):
        if name.startswith("_"):
            continue
        if getattr(obj, "__module__", None) != module.__name__:
            continue
        if inspect.isclass(obj) and is_dataclass(obj):
            dcs.append((name, obj))
        elif inspect.isfunction(obj):
            funcs.append((name, obj))
    funcs.sort(key=lambda x: x[0])
    dcs.sort(key=lambda x: x[0])
    return funcs, dcs


def _format_signature(func) -> str:
    sig = inspect.signature(func)
    return f"{func.__name__}{sig}"


def _format_docstring(obj) -> str:
    doc = inspect.getdoc(obj) or "_(no docstring)_"
    return doc


def _format_dataclass(name: str, cls) -> str:
    lines = [f"### `class {name}`", ""]
    doc = inspect.getdoc(cls)
    if doc:
        lines.append(doc)
        lines.append("")
    lines.append("| Field | Type | Default |")
    lines.append("|---|---|---|")
    for f in fields(cls):
        type_repr = (
            f.type.__name__ if inspect.isclass(f.type) else str(f.type)
        )
        # Clean up some common verbose type reprs
        type_repr = re.sub(r"typing\.", "", type_repr)
        if f.default is not inspect.Parameter.empty and f.default.__class__.__name__ != "_MISSING_TYPE":
            default = f"`{f.default!r}`"
        elif f.default_factory.__class__.__name__ != "_MISSING_TYPE":  # type: ignore[union-attr]
            default = f"`{f.default_factory.__name__}()`"
        else:
            default = "—"
        lines.append(f"| `{f.name}` | `{type_repr}` | {default} |")
    lines.append("")
    return "\n".join(lines)


def _format_function(name: str, func) -> str:
    sig = _format_signature(func)
    doc = _format_docstring(func)
    return "\n".join(
        [
            f"### `{name}()`",
            "",
            f"```python",
            f"def {sig}",
            f"```",
            "",
            doc,
            "",
        ]
    )


def _render_module(mod_name: str, module: ModuleType) -> str:
    """Produce the full Markdown body for one module.

    `mod_name` is the importable dotted name (e.g. "lib.discovery"); the
    rendered file path uses the short form (`lib/discovery.py`).
    """
    funcs, dcs = _public_members(module)
    mod_doc = inspect.getdoc(module) or ""
    short = mod_name.rsplit(".", 1)[-1]

    parts: list[str] = []
    parts.append(f"# `lib/{short}.py` — API Reference")
    parts.append("")
    parts.append(
        "> Auto-generated by `scripts/gen_lib_reference.py`. "
        "Do not edit by hand — re-run the generator to update."
    )
    parts.append("")
    if mod_doc:
        parts.append("## Module overview")
        parts.append("")
        parts.append(mod_doc)
        parts.append("")

    if dcs:
        parts.append("## Dataclasses")
        parts.append("")
        for name, cls in dcs:
            parts.append(_format_dataclass(name, cls))

    if funcs:
        parts.append("## Functions")
        parts.append("")
        for name, func in funcs:
            parts.append(_format_function(name, func))

    return "\n".join(parts).rstrip() + "\n"


def _load_modules() -> dict[str, ModuleType]:
    # lib/ is now a real Python package — add the *parent* (repo root)
    # to sys.path so `import lib.discovery` resolves correctly.
    sys.path.insert(0, str(REPO_ROOT))
    out = {}
    for name in MODULES:
        # Reload to pick up edits if running interactively.
        if name in sys.modules:
            del sys.modules[name]
        out[name] = importlib.import_module(name)
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if generated files would differ from disk.",
    )
    args = parser.parse_args(argv)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    modules = _load_modules()

    drift = False
    for name, mod in modules.items():
        # Output filename uses the short module name (e.g. "lib.discovery" → "discovery.md")
        short_name = name.rsplit(".", 1)[-1]
        target = OUT_DIR / f"{short_name}.md"
        new_content = _render_module(name, mod)
        if args.check:
            existing = target.read_text(encoding="utf-8") if target.exists() else ""
            if existing != new_content:
                print(f"DRIFT: {target.relative_to(REPO_ROOT)}", file=sys.stderr)
                drift = True
        else:
            target.write_text(new_content, encoding="utf-8")
            print(f"wrote {target.relative_to(REPO_ROOT)}")

    if args.check and drift:
        print("Reference docs are stale. Run: python3 scripts/gen_lib_reference.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
